( assembler words )
enum-start : asm-nop ( -- n ) literal ;
enum-next  : asm-add ( -- n ) literal ;
enum-next  : asm-sub ( -- n ) literal ;
enum-next  : asm-mul ( -- n ) literal ;
enum-next  : asm-div ( -- n ) literal ;
enum-next  : asm-rem ( -- n ) literal ;
enum-next  : asm-shl ( -- n ) literal ;
enum-next  : asm-shr ( -- n ) literal ;
enum-next  : asm-and ( -- n ) literal ;
enum-next  : asm-or ( -- n ) literal ;
enum-next  : asm-not ( -- n ) literal ;
enum-next  : asm-xor ( -- n ) literal ;
enum-next  : asm-nand ( -- n ) literal ;
enum-next  : asm-nor ( -- n ) literal ;
enum-next  : asm-addi ( -- n ) literal ;
enum-next  : asm-subi ( -- n ) literal ;
enum-next  : asm-muli ( -- n ) literal ;
enum-next  : asm-divi ( -- n ) literal ;
enum-next  : asm-remi ( -- n ) literal ;
enum-next  : asm-shli ( -- n ) literal ;
enum-next  : asm-shri ( -- n ) literal ;
enum-next  : asm-min ( -- n ) literal ;
enum-next  : asm-max ( -- n ) literal ;
enum-next  : asm-lxor ( -- n ) literal ;
enum-next  : asm-lnot ( -- n ) literal ;
enum-next  : asm-land ( -- n ) literal ;
enum-next  : asm-lor ( -- n ) literal ;
enum-next  : asm-lnand ( -- n ) literal ;
enum-next  : asm-lnor ( -- n ) literal ;
enum-next  : asm-eq ( -- n ) literal ;
enum-next  : asm-eqi ( -- n ) literal ;
enum-next  : asm-neq ( -- n ) literal ;
enum-next  : asm-neqi ( -- n ) literal ;
enum-next  : asm-lt ( -- n ) literal ;
enum-next  : asm-lti ( -- n ) literal ;
enum-next  : asm-gt ( -- n ) literal ;
enum-next  : asm-gti ( -- n ) literal ;
enum-next  : asm-le ( -- n ) literal ;
enum-next  : asm-lei ( -- n ) literal ;
enum-next  : asm-ge ( -- n ) literal ;
enum-next  : asm-gei ( -- n ) literal ;
enum-next  : asm-move ( -- n ) literal ;
enum-next  : asm-set ( -- n ) literal ;
enum-next  : asm-swap ( -- n ) literal ;
enum-next  : asm-ld ( -- n ) literal ;
enum-next  : asm-ldi ( -- n ) literal ;
enum-next  : asm-ldwo ( -- n ) literal ;
enum-next  : asm-st ( -- n ) literal ;
enum-next  : asm-sti ( -- n ) literal ;
enum-next  : asm-stwo ( -- n ) literal ;
enum-next  : asm-push ( -- n ) literal ;
enum-next  : asm-pushi ( -- n ) literal ;
enum-next  : asm-pop ( -- n ) literal ;
enum-next  : asm-ldc ( -- n ) literal ;
enum-next  : asm-stc ( -- n ) literal ;
enum-next  : asm-b ( -- n ) literal ;
enum-next  : asm-bl ( -- n ) literal ;
enum-next  : asm-br ( -- n ) literal ;
enum-next  : asm-brl ( -- n ) literal ;
enum-next  : asm-bc ( -- n ) literal ;
enum-next  : asm-bcr ( -- n ) literal ;
enum-next  : asm-bcrl ( -- n ) literal ;
enum-next  : asm-terminateExecution ( -- n ) literal ;
enum-done



close-input-file
