\ used for the purposes of data definitions
: {opcode ( -- 0 ) 0 ;
: opcode} ( n -- ) drop ;
: opcode: ( n -- n+1 ) dup constant 1+ ;
{opcode 
opcode: #illegal  
opcode: #add
opcode: #sub      
opcode: #mul
opcode: #div
opcode: #rem
opcode: #lshift   
opcode: #rshift   
opcode: #and      
opcode: #or       
opcode: #invert   
opcode: #xor      
opcode: #min      
opcode: #max      
opcode: #eq       
opcode: #neq      
opcode: #lt       
opcode: #gt       
opcode: #le       
opcode: #ge       
opcode: #set      
opcode: #ld
opcode: #st
opcode: #push     
opcode: #pop      
opcode: #br       
opcode: #brl      
opcode: #bcr      
opcode: #bcrl     
opcode: #ueq      
opcode: #uneq     
opcode: #ult      
opcode: #ugt      
opcode: #ule      
opcode: #uge      
opcode: #uand     
opcode: #uor      
opcode: #uinvert  
opcode: #uxor     
opcode: #umin     
opcode: #umax     
opcode: #uadd     
opcode: #usub     
opcode: #umul     
opcode: #udiv     
opcode: #urem     
opcode: #ulshift  
opcode: #urshift  
opcode: #incr     
opcode: #decr     
opcode: #uincr    
opcode: #udecr    
opcode: #call     
opcode: #condb    
opcode: #addi     
opcode: #subi     
opcode: #rshifti  
opcode: #lshifti  
opcode: #ldtincr  
opcode: #lti      
opcode: #move     
opcode: #sttincr  
opcode: #addw     
opcode: #subw     
opcode: #pushw    
opcode: #popw     
opcode: #return   
opcode: #creturn  
opcode: #invertw  
opcode: #bi       
opcode: #eqz      
opcode: #neqz     
opcode: #ltz      
opcode: #gtz      
opcode: #lez      
opcode: #gez      
opcode: #andi     
opcode: #uandi    
opcode: #muli     
opcode: #divi     
opcode: #pushi    
opcode: #memincr  
opcode: #memdecr  
opcode: #stop     \ stop execution
opcode}
